// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_multi_withdrawal_rules

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.MultiWithdrawalRule, error)
	CreateOrUpdate(ctx context.Context, arg CreateOrUpdateParams) error
	GetByWalletID(ctx context.Context, withdrawalWalletID uuid.UUID) (*models.MultiWithdrawalRule, error)
	RemoveByWalletID(ctx context.Context, withdrawalWalletID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
