// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_withdrawal_wallets

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.WithdrawalWallet, error)
	GetById(ctx context.Context, id uuid.UUID) (*models.WithdrawalWallet, error)
	GetForMultiWithdrawal(ctx context.Context, userID uuid.NullUUID) ([]*GetForMultiWithdrawalRow, error)
	GetWalletsForWithdrawal(ctx context.Context, blockchain models.Blockchain) ([]*models.WithdrawalWallet, error)
	GetWithdrawalWalletByCurrency(ctx context.Context, arg GetWithdrawalWalletByCurrencyParams) (*models.WithdrawalWallet, error)
	GetWithdrawalWallets(ctx context.Context, userID uuid.UUID) ([]*models.WithdrawalWallet, error)
	Update(ctx context.Context, arg UpdateParams) (*models.WithdrawalWallet, error)
}

var _ Querier = (*Queries)(nil)
