// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: aml_supported_assets_gen.sql

package repo_aml_supported_assets

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"
)

const find = `-- name: Find :many
SELECT service_slug, currency_id, asset_identity, blockchain_name FROM aml_supported_assets
`

func (q *Queries) Find(ctx context.Context) ([]*models.AmlSupportedAsset, error) {
	rows, err := q.db.Query(ctx, find)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.AmlSupportedAsset{}
	for rows.Next() {
		var i models.AmlSupportedAsset
		if err := rows.Scan(
			&i.ServiceSlug,
			&i.CurrencyID,
			&i.AssetIdentity,
			&i.BlockchainName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
