// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_user_notifications

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.UserNotification, error)
	CreateOrUpdate(ctx context.Context, arg []CreateOrUpdateParams) *CreateOrUpdateBatchResults
	GetByID(ctx context.Context, id uuid.UUID) (*models.UserNotification, error)
	GetByUserAndID(ctx context.Context, arg GetByUserAndIDParams) (*GetByUserAndIDRow, error)
	GetUserListWithCategory(ctx context.Context, userID uuid.UUID) ([]*GetUserListWithCategoryRow, error)
	GetUserNotificationChannels(ctx context.Context, arg GetUserNotificationChannelsParams) (*GetUserNotificationChannelsRow, error)
}

var _ Querier = (*Queries)(nil)
