// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_personal_access_tokens

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"

	"github.com/google/uuid"
)

type Querier interface {
	ClearAllByUser(ctx context.Context, tokenableID uuid.UUID) error
	Create(ctx context.Context, arg CreateParams) (*models.PersonalAccessToken, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByToken(ctx context.Context, token string) (*models.PersonalAccessToken, error)
}

var _ Querier = (*Queries)(nil)
