// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_user_stores

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	CheckStoreHasUser(ctx context.Context, arg CheckStoreHasUserParams) (bool, error)
	Create(ctx context.Context, arg CreateParams) (*models.UserStore, error)
	GetStoreIDsByUser(ctx context.Context, arg GetStoreIDsByUserParams) ([]uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
