// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_stores_gen.sql

package repo_user_stores

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO user_stores (user_id, store_id, created_at)
	VALUES ($1, $2, now())
	RETURNING id, user_id, store_id, created_at
`

type CreateParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	StoreID uuid.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.UserStore, error) {
	row := q.db.QueryRow(ctx, create, arg.UserID, arg.StoreID)
	var i models.UserStore
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.CreatedAt,
	)
	return &i, err
}
