// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_user_exchange_pairs

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.UserExchangePair, error)
	Delete(ctx context.Context, arg DeleteParams) error
	DeleteByUserAndExchangeID(ctx context.Context, arg DeleteByUserAndExchangeIDParams) error
	Find(ctx context.Context, arg FindParams) ([]*models.UserExchangePair, error)
	GetAll(ctx context.Context) ([]*models.UserExchangePair, error)
	UpdatePairs(ctx context.Context, arg []UpdatePairsParams) *UpdatePairsBatchResults
}

var _ Querier = (*Queries)(nil)
