// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_update_balance_queue

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.UpdateBalanceQueue, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetQueuedWithCurrency(ctx context.Context) ([]*GetQueuedWithCurrencyRow, error)
}

var _ Querier = (*Queries)(nil)
