// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_exchange_withdrawal_settings

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	ChangeAddress(ctx context.Context, arg ChangeAddressParams) error
	ChangeMinAmount(ctx context.Context, arg ChangeMinAmountParams) error
	Create(ctx context.Context, arg CreateParams) (*models.ExchangeWithdrawalSetting, error)
	Delete(ctx context.Context, arg DeleteParams) error
	DeleteByUserAndExchangeID(ctx context.Context, arg DeleteByUserAndExchangeIDParams) error
	GetActive(ctx context.Context) ([]*models.ExchangeWithdrawalSetting, error)
	GetAllAddressesWithEnabledCurr(ctx context.Context, userID uuid.UUID) ([]*GetAllAddressesWithEnabledCurrRow, error)
	GetAllByUser(ctx context.Context, arg GetAllByUserParams) ([]*models.ExchangeWithdrawalSetting, error)
	GetByID(ctx context.Context, arg GetByIDParams) (*models.ExchangeWithdrawalSetting, error)
	GetExisting(ctx context.Context, arg GetExistingParams) (*models.ExchangeWithdrawalSetting, error)
	Update(ctx context.Context, arg UpdateParams) (*models.ExchangeWithdrawalSetting, error)
	UpdateIsEnabledByID(ctx context.Context, arg UpdateIsEnabledByIDParams) (*models.ExchangeWithdrawalSetting, error)
	UpdateIsEnabledByUserAndExchangeID(ctx context.Context, arg UpdateIsEnabledByUserAndExchangeIDParams) error
}

var _ Querier = (*Queries)(nil)
