// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_exchange_withdrawal_history

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"

	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.ExchangeWithdrawalHistory, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.ExchangeWithdrawalHistory, error)
	GetByUserAndOrderID(ctx context.Context, arg GetByUserAndOrderIDParams) (*GetByUserAndOrderIDRow, error)
	Update(ctx context.Context, arg UpdateParams) error
}

var _ Querier = (*Queries)(nil)
