// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aml_check_queue_gen.sql

package repo_aml_check_queue

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :exec
INSERT INTO aml_check_queue (user_id, aml_check_id, created_at, request_payload)
	VALUES ($1, $2, now(), $3)
`

func (q *Queries) Create(ctx context.Context, userID uuid.UUID, amlCheckID uuid.UUID, requestPayload []byte) error {
	_, err := q.db.Exec(ctx, create, userID, amlCheckID, requestPayload)
	return err
}
