// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_aml_check_queue

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, userID uuid.UUID, amlCheckID uuid.UUID) error
	Delete(ctx context.Context, id uuid.UUID) error
	FetchPending(ctx context.Context, maxQueueAttempts int32, pendingStatus models.AMLCheckStatus) ([]*FetchPendingRow, error)
	IncrementAttempts(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
