// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_wallet_addresses_activity_logs

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.WalletAddressesActivityLog, error)
	GetLogByWalletAddressID(ctx context.Context, walletAddressesID uuid.UUID) ([]*models.WalletAddressesActivityLog, error)
}

var _ Querier = (*Queries)(nil)
