// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_addresses_activity_logs.sql

package repo_wallet_addresses_activity_logs

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

const getLogByWalletAddressID = `-- name: GetLogByWalletAddressID :many
SELECT id, wallet_addresses_id, text, text_variables, created_at, updated_at FROM wallet_addresses_activity_logs WHERE wallet_addresses_id = $1 ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) GetLogByWalletAddressID(ctx context.Context, walletAddressesID uuid.UUID) ([]*models.WalletAddressesActivityLog, error) {
	rows, err := q.db.Query(ctx, getLogByWalletAddressID, walletAddressesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.WalletAddressesActivityLog{}
	for rows.Next() {
		var i models.WalletAddressesActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.WalletAddressesID,
			&i.Text,
			&i.TextVariables,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
