CREATE TABLE IF NOT EXISTS monitor_types (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    slug VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    error_count INT NOT NULL DEFAULT 0,
    error_count_notify_limit INT NOT NULL DEFAULT 3,
    start_params JSONB NOT NULL DEFAULT '{}',
    notify_params JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);