CREATE TABLE monitors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    monitor_type_id INT NOT NULL,
    failed BOOLEAN NOT NULL DEFAULT FALSE,
    finished BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);