ALTER TABLE user_address_book
    ALTER COLUMN currency_id SET NOT NULL,
    ALTER COLUMN submitted_at TYPE TIMESTAMP WITHOUT TIME ZONE USING submitted_at,
	ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at,
	ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE USING updated_at,
	ALTER COLUMN deleted_at TYPE TIMESTAMP WITHOUT TIME ZONE USING deleted_at;