// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aml_services_gen.sql

package repo_aml_services

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

const getByID = `-- name: GetByID :one
SELECT id, slug, created_at, updated_at FROM aml_services WHERE id=$1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.AmlService, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.AmlService
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
