// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_aml_services

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	GetByID(ctx context.Context, id uuid.UUID) (*models.AmlService, error)
}

var _ Querier = (*Queries)(nil)
