// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_store_api_keys

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.StoreApiKey, error)
	Delete(ctx context.Context, id uuid.UUID) error
	DisableByStore(ctx context.Context, storeID uuid.UUID) error
	EnableByStore(ctx context.Context, storeID uuid.UUID) error
	GetById(ctx context.Context, id uuid.UUID) (*models.StoreApiKey, error)
	GetByStoreId(ctx context.Context, storeID uuid.UUID) ([]*models.StoreApiKey, error)
	GetStoreByKey(ctx context.Context, key string) (*models.Store, error)
	UpdateKey(ctx context.Context, arg UpdateKeyParams) (*models.StoreApiKey, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*models.StoreApiKey, error)
}

var _ Querier = (*Queries)(nil)
