// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_webhook_send_queue

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"

	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.WebhookSendQueue, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetById(ctx context.Context, id uuid.UUID) (*models.WebhookSendQueue, error)
	GetQueuedWebhooks(ctx context.Context) ([]*GetQueuedWebhooksRow, error)
	UpdateDelay(ctx context.Context, arg UpdateDelayParams) error
}

var _ Querier = (*Queries)(nil)
