// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_store_currencies

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	CreateOne(ctx context.Context, arg CreateOneParams) error
	Delete(ctx context.Context, arg DeleteParams) error
	FindAllByStoreID(ctx context.Context, storeID uuid.UUID) ([]*models.StoreCurrency, error)
	FindByStoreID(ctx context.Context, arg FindByStoreIDParams) (*models.StoreCurrency, error)
	GetAllByStoreID(ctx context.Context, storeID uuid.UUID) ([]*models.Currency, error)
}

var _ Querier = (*Queries)(nil)
