// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_wallets

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Wallet, error)
	GetById(ctx context.Context, id uuid.UUID) (*models.Wallet, error)
	GetByStore(ctx context.Context, arg GetByStoreParams) (*models.Wallet, error)
	GetFullDataByID(ctx context.Context, id uuid.UUID) (*GetFullDataByIDRow, error)
	GetWalletWithStore(ctx context.Context, arg GetWalletWithStoreParams) ([]*GetWalletWithStoreRow, error)
	RestoreByStore(ctx context.Context, storeID uuid.UUID) ([]uuid.UUID, error)
	SearchByParam(ctx context.Context, arg SearchByParamParams) ([]*SearchByParamRow, error)
	SoftDeleteByStore(ctx context.Context, storeID uuid.UUID) ([]uuid.UUID, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserIPAddress(ctx context.Context, arg UpdateUserIPAddressParams) error
	UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) error
	UpdateUserUntrustedEmail(ctx context.Context, arg UpdateUserUntrustedEmailParams) error
}

var _ Querier = (*Queries)(nil)
