// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocked_transactions.sql

package repo_blocked_transactions

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

const getUnclaimedByWalletID = `-- name: GetUnclaimedByWalletID :many
SELECT bt.id, bt.user_id, bt.store_id, bt.transaction_id, bt.aml_check_id, bt.wallet_id, bt.risk_level, bt.score, bt.created_at, bt.updated_at
FROM blocked_transactions bt
WHERE bt.wallet_id = $1
  AND NOT EXISTS (
    SELECT 1
    FROM refund_requests rr
    WHERE rr.blocked_transaction_id = bt.id
  )
ORDER BY bt.created_at DESC
`

func (q *Queries) GetUnclaimedByWalletID(ctx context.Context, walletID uuid.UUID) ([]*models.BlockedTransaction, error) {
	rows, err := q.db.Query(ctx, getUnclaimedByWalletID, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.BlockedTransaction{}
	for rows.Next() {
		var i models.BlockedTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreID,
			&i.TransactionID,
			&i.AmlCheckID,
			&i.WalletID,
			&i.RiskLevel,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
