// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocked_transactions_gen.sql

package repo_blocked_transactions

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const create = `-- name: Create :one
INSERT INTO blocked_transactions (user_id, store_id, transaction_id, aml_check_id, wallet_id, risk_level, score, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, now())
	RETURNING id, user_id, store_id, transaction_id, aml_check_id, wallet_id, risk_level, score, created_at, updated_at
`

type CreateParams struct {
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	StoreID       uuid.UUID       `db:"store_id" json:"store_id"`
	TransactionID uuid.UUID       `db:"transaction_id" json:"transaction_id"`
	AmlCheckID    uuid.UUID       `db:"aml_check_id" json:"aml_check_id"`
	WalletID      uuid.UUID       `db:"wallet_id" json:"wallet_id"`
	RiskLevel     string          `db:"risk_level" json:"risk_level"`
	Score         decimal.Decimal `db:"score" json:"score"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.BlockedTransaction, error) {
	row := q.db.QueryRow(ctx, create,
		arg.UserID,
		arg.StoreID,
		arg.TransactionID,
		arg.AmlCheckID,
		arg.WalletID,
		arg.RiskLevel,
		arg.Score,
	)
	var i models.BlockedTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.TransactionID,
		&i.AmlCheckID,
		&i.WalletID,
		&i.RiskLevel,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAllByWalletID = `-- name: GetAllByWalletID :many
SELECT id, user_id, store_id, transaction_id, aml_check_id, wallet_id, risk_level, score, created_at, updated_at FROM blocked_transactions WHERE wallet_id=$1
`

func (q *Queries) GetAllByWalletID(ctx context.Context, walletID uuid.UUID) ([]*models.BlockedTransaction, error) {
	rows, err := q.db.Query(ctx, getAllByWalletID, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.BlockedTransaction{}
	for rows.Next() {
		var i models.BlockedTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreID,
			&i.TransactionID,
			&i.AmlCheckID,
			&i.WalletID,
			&i.RiskLevel,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getById = `-- name: GetById :one
SELECT id, user_id, store_id, transaction_id, aml_check_id, wallet_id, risk_level, score, created_at, updated_at FROM blocked_transactions WHERE id=$1 LIMIT 1
`

func (q *Queries) GetById(ctx context.Context, id uuid.UUID) (*models.BlockedTransaction, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i models.BlockedTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.TransactionID,
		&i.AmlCheckID,
		&i.WalletID,
		&i.RiskLevel,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
