// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo_blocked_transactions

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.BlockedTransaction, error)
	GetAllByWalletID(ctx context.Context, walletID uuid.UUID) ([]*models.BlockedTransaction, error)
	GetAllWithTxByWalletID(ctx context.Context, walletID uuid.UUID) ([]*GetAllWithTxByWalletIDRow, error)
	GetById(ctx context.Context, id uuid.UUID) (*models.BlockedTransaction, error)
	GetUnclaimedByWalletID(ctx context.Context, walletID uuid.UUID) ([]*GetUnclaimedByWalletIDRow, error)
}

var _ Querier = (*Queries)(nil)
