// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	key_value "github.com/dv-net/dv-merchant/pkg/key_value"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IKeyValue is an autogenerated mock type for the IKeyValue type
type IKeyValue struct {
	mock.Mock
}

type IKeyValue_Expecter struct {
	mock *mock.Mock
}

func (_m *IKeyValue) EXPECT() *IKeyValue_Expecter {
	return &IKeyValue_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *IKeyValue) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IKeyValue_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type IKeyValue_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *IKeyValue_Expecter) Close() *IKeyValue_Close_Call {
	return &IKeyValue_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *IKeyValue_Close_Call) Run(run func()) *IKeyValue_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IKeyValue_Close_Call) Return(_a0 error) *IKeyValue_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IKeyValue_Close_Call) RunAndReturn(run func() error) *IKeyValue_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, key
func (_m *IKeyValue) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IKeyValue_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IKeyValue_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *IKeyValue_Expecter) Delete(ctx interface{}, key interface{}) *IKeyValue_Delete_Call {
	return &IKeyValue_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *IKeyValue_Delete_Call) Run(run func(ctx context.Context, key string)) *IKeyValue_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IKeyValue_Delete_Call) Return(_a0 error) *IKeyValue_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IKeyValue_Delete_Call) RunAndReturn(run func(context.Context, string) error) *IKeyValue_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *IKeyValue) Get(ctx context.Context, key string) (key_value.KeyValueResult, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 key_value.KeyValueResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (key_value.KeyValueResult, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) key_value.KeyValueResult); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(key_value.KeyValueResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IKeyValue_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IKeyValue_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *IKeyValue_Expecter) Get(ctx interface{}, key interface{}) *IKeyValue_Get_Call {
	return &IKeyValue_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *IKeyValue_Get_Call) Run(run func(ctx context.Context, key string)) *IKeyValue_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IKeyValue_Get_Call) Return(_a0 key_value.KeyValueResult, _a1 error) *IKeyValue_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IKeyValue_Get_Call) RunAndReturn(run func(context.Context, string) (key_value.KeyValueResult, error)) *IKeyValue_Get_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementCounterWithLimit provides a mock function with given fields: ctx, key, counterMax, ttl
func (_m *IKeyValue) IncrementCounterWithLimit(ctx context.Context, key string, counterMax int64, ttl time.Duration) error {
	ret := _m.Called(ctx, key, counterMax, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IncrementCounterWithLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, time.Duration) error); ok {
		r0 = rf(ctx, key, counterMax, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IKeyValue_IncrementCounterWithLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementCounterWithLimit'
type IKeyValue_IncrementCounterWithLimit_Call struct {
	*mock.Call
}

// IncrementCounterWithLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - counterMax int64
//   - ttl time.Duration
func (_e *IKeyValue_Expecter) IncrementCounterWithLimit(ctx interface{}, key interface{}, counterMax interface{}, ttl interface{}) *IKeyValue_IncrementCounterWithLimit_Call {
	return &IKeyValue_IncrementCounterWithLimit_Call{Call: _e.mock.On("IncrementCounterWithLimit", ctx, key, counterMax, ttl)}
}

func (_c *IKeyValue_IncrementCounterWithLimit_Call) Run(run func(ctx context.Context, key string, counterMax int64, ttl time.Duration)) *IKeyValue_IncrementCounterWithLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(time.Duration))
	})
	return _c
}

func (_c *IKeyValue_IncrementCounterWithLimit_Call) Return(_a0 error) *IKeyValue_IncrementCounterWithLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IKeyValue_IncrementCounterWithLimit_Call) RunAndReturn(run func(context.Context, string, int64, time.Duration) error) *IKeyValue_IncrementCounterWithLimit_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, expiration
func (_m *IKeyValue) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) error {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IKeyValue_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type IKeyValue_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *IKeyValue_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *IKeyValue_Set_Call {
	return &IKeyValue_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *IKeyValue_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *IKeyValue_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *IKeyValue_Set_Call) Return(_a0 error) *IKeyValue_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IKeyValue_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *IKeyValue_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewIKeyValue creates a new instance of IKeyValue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIKeyValue(t interface {
	mock.TestingT
	Cleanup(func())
}) *IKeyValue {
	mock := &IKeyValue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
