// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_store_secrets

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"

	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.StoreSecret, error)
	DeleteBuStoreID(ctx context.Context, storeID uuid.UUID) error
	GetSecretByStoreID(ctx context.Context, storeID uuid.UUID) (string, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (*models.StoreSecret, error)
}

var _ Querier = (*Queries)(nil)
