// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_unconfirmed_transactions

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	CollapseAllByConfirmedDeposit(ctx context.Context) error
	Create(ctx context.Context, arg CreateParams) (*models.UnconfirmedTransaction, error)
	DeleteByTxHash(ctx context.Context, id uuid.UUID) error
	GetAllTransfer(ctx context.Context) ([]*models.UnconfirmedTransaction, error)
	GetById(ctx context.Context, id uuid.UUID) (*models.UnconfirmedTransaction, error)
	GetByType(ctx context.Context, arg GetByTypeParams) ([]*models.UnconfirmedTransaction, error)
	GetOneByHashAndBlockchain(ctx context.Context, arg GetOneByHashAndBlockchainParams) (*models.UnconfirmedTransaction, error)
}

var _ Querier = (*Queries)(nil)
