// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_tron_wallet_balance_statistics

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
)

type Querier interface {
	ApproximateByResolution(ctx context.Context, arg ApproximateByResolutionParams) ([]*ApproximateByResolutionRow, error)
	Create(ctx context.Context, arg CreateParams) (*models.TronWalletBalanceStatistic, error)
	InsertTronWalletBalanceStatisticsBatch(ctx context.Context, arg []InsertTronWalletBalanceStatisticsBatchParams) *InsertTronWalletBalanceStatisticsBatchBatchResults
}

var _ Querier = (*Queries)(nil)
