// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo_user_aml_settings

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	GetByUserID(ctx context.Context, userID uuid.UUID) (*models.UserAmlSetting, error)
	ListRiskRulesByUserID(ctx context.Context, arg ListRiskRulesByUserIDParams) ([]*models.UserAmlRiskRule, error)
	UpsertAmlRiskRule(ctx context.Context, arg UpsertAmlRiskRuleParams) (*models.UserAmlRiskRule, error)
	UpsertAmlSetting(ctx context.Context, arg UpsertAmlSettingParams) (*models.UserAmlSetting, error)
}

var _ Querier = (*Queries)(nil)
