// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_aml_risk_rules.sql

package repo_user_aml_settings

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const listRiskRulesByUserID = `-- name: ListRiskRulesByUserID :many
SELECT id, user_id, provider_slug, risk_type, enabled, threshold, action, created_at, updated_at
FROM user_aml_risk_rules
WHERE user_id = $1
  AND provider_slug = $2
ORDER BY risk_type
`

type ListRiskRulesByUserIDParams struct {
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	ProviderSlug string    `db:"provider_slug" json:"provider_slug"`
}

func (q *Queries) ListRiskRulesByUserID(ctx context.Context, arg ListRiskRulesByUserIDParams) ([]*models.UserAmlRiskRule, error) {
	rows, err := q.db.Query(ctx, listRiskRulesByUserID, arg.UserID, arg.ProviderSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.UserAmlRiskRule{}
	for rows.Next() {
		var i models.UserAmlRiskRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderSlug,
			&i.RiskType,
			&i.Enabled,
			&i.Threshold,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAmlRiskRule = `-- name: UpsertAmlRiskRule :one
INSERT INTO user_aml_risk_rules (user_id, provider_slug, risk_type, enabled, threshold, action,
                                 created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now()) ON CONFLICT (user_id, provider_slug, risk_type) DO
UPDATE
    SET enabled = EXCLUDED.enabled,
    threshold = EXCLUDED.threshold,
    action = EXCLUDED.action,
    updated_at = now()
    RETURNING id, user_id, provider_slug, risk_type, enabled, threshold, action, created_at, updated_at
`

type UpsertAmlRiskRuleParams struct {
	UserID       uuid.UUID       `db:"user_id" json:"user_id"`
	ProviderSlug string          `db:"provider_slug" json:"provider_slug"`
	RiskType     string          `db:"risk_type" json:"risk_type"`
	Enabled      bool            `db:"enabled" json:"enabled"`
	Threshold    decimal.Decimal `db:"threshold" json:"threshold"`
	Action       string          `db:"action" json:"action"`
}

func (q *Queries) UpsertAmlRiskRule(ctx context.Context, arg UpsertAmlRiskRuleParams) (*models.UserAmlRiskRule, error) {
	row := q.db.QueryRow(ctx, upsertAmlRiskRule,
		arg.UserID,
		arg.ProviderSlug,
		arg.RiskType,
		arg.Enabled,
		arg.Threshold,
		arg.Action,
	)
	var i models.UserAmlRiskRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderSlug,
		&i.RiskType,
		&i.Enabled,
		&i.Threshold,
		&i.Action,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
