// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_aml_settings.sql

package repo_user_aml_settings

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

const getByUserID = `-- name: GetByUserID :one
SELECT id, enabled, provider_slug, created_at, updated_at, user_id
FROM user_aml_settings
WHERE user_id = $1 limit 1
`

func (q *Queries) GetByUserID(ctx context.Context, userID uuid.UUID) (*models.UserAmlSetting, error) {
	row := q.db.QueryRow(ctx, getByUserID, userID)
	var i models.UserAmlSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.ProviderSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const upsertAmlSetting = `-- name: UpsertAmlSetting :one
INSERT INTO user_aml_settings (user_id, enabled, provider_slug, created_at, updated_at)
VALUES ($1, $2, $3, now(), now()) ON CONFLICT (user_id) DO
UPDATE
    SET enabled = EXCLUDED.enabled,
    provider_slug = EXCLUDED.provider_slug,
    updated_at = now()
    RETURNING id, enabled, provider_slug, created_at, updated_at, user_id
`

type UpsertAmlSettingParams struct {
	UserID       uuid.UUID       `db:"user_id" json:"user_id"`
	Enabled      bool            `db:"enabled" json:"enabled"`
	ProviderSlug *models.AMLSlug `db:"provider_slug" json:"provider_slug"`
}

func (q *Queries) UpsertAmlSetting(ctx context.Context, arg UpsertAmlSettingParams) (*models.UserAmlSetting, error) {
	row := q.db.QueryRow(ctx, upsertAmlSetting, arg.UserID, arg.Enabled, arg.ProviderSlug)
	var i models.UserAmlSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.ProviderSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}
