// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_notification_send_queue

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.NotificationSendQueue, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetById(ctx context.Context, id uuid.UUID) (*models.NotificationSendQueue, error)
	GetQueuedNotifications(ctx context.Context, maxAttempts int32) ([]*models.NotificationSendQueue, error)
	IncreaseAttempts(ctx context.Context, id uuid.UUID) (int32, error)
}

var _ Querier = (*Queries)(nil)
