// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package repo_transfers

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchDeleteTransfers = `-- name: BatchDeleteTransfers :batchexec
DELETE FROM transfers WHERE id = $1 AND user_id = $2 AND status = 'failed'
`

type BatchDeleteTransfersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchDeleteTransfersParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) BatchDeleteTransfers(ctx context.Context, arg []BatchDeleteTransfersParams) *BatchDeleteTransfersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.UserID,
		}
		batch.Queue(batchDeleteTransfers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchDeleteTransfersBatchResults{br, len(arg), false}
}

func (b *BatchDeleteTransfersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchDeleteTransfersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
