// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_settings

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Setting, error)
	DeleteByNameAndModelID(ctx context.Context, arg DeleteByNameAndModelIDParams) error
	DeleteRootByName(ctx context.Context, name string) error
	GetAllByModel(ctx context.Context, arg GetAllByModelParams) ([]*models.Setting, error)
	GetAllRootSettings(ctx context.Context) ([]*models.Setting, error)
	GetByModel(ctx context.Context, arg GetByModelParams) (*models.Setting, error)
	GetByName(ctx context.Context, name string) (*models.Setting, error)
	GetByNames(ctx context.Context, settingNames []string) ([]*models.Setting, error)
	Update(ctx context.Context, arg UpdateParams) (*models.Setting, error)
	UpdateSettingsWithReplace(ctx context.Context, arg []UpdateSettingsWithReplaceParams) *UpdateSettingsWithReplaceBatchResults
}

var _ Querier = (*Queries)(nil)
