// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_invoice_addresses

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.InvoiceAddress, error)
	CreateWithWalletAddress(ctx context.Context, arg CreateWithWalletAddressParams) (*CreateWithWalletAddressRow, error)
	GetByIDWithAddress(ctx context.Context, id uuid.UUID) (*GetByIDWithAddressRow, error)
	GetByInvoiceID(ctx context.Context, invoiceID uuid.UUID) ([]*GetByInvoiceIDRow, error)
	GetByWalletAddressID(ctx context.Context, walletAddressID uuid.UUID) (*GetByWalletAddressIDRow, error)
	GetInvoiceAddressByInvoiceAndCurrency(ctx context.Context, arg GetInvoiceAddressByInvoiceAndCurrencyParams) (*GetInvoiceAddressByInvoiceAndCurrencyRow, error)
}

var _ Querier = (*Queries)(nil)
