// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_log_types

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.LogType, error)
	GetAll(ctx context.Context) ([]*models.LogType, error)
	GetByID(ctx context.Context, id int32) (*models.LogType, error)
	GetBySlug(ctx context.Context, slug string) (*models.LogType, error)
	Update(ctx context.Context, arg UpdateParams) (*models.LogType, error)
}

var _ Querier = (*Queries)(nil)
