// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_store_webhooks

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.StoreWebhook, error)
	Delete(ctx context.Context, id uuid.UUID) error
	DisableAllByStore(ctx context.Context, storeID uuid.UUID) error
	EnableAllByStore(ctx context.Context, storeID uuid.UUID) error
	GetById(ctx context.Context, id uuid.UUID) (*models.StoreWebhook, error)
	GetByStoreAndType(ctx context.Context, arg GetByStoreAndTypeParams) ([]*GetByStoreAndTypeRow, error)
	GetByStoreId(ctx context.Context, storeID uuid.UUID) ([]*models.StoreWebhook, error)
	Update(ctx context.Context, arg UpdateParams) (*models.StoreWebhook, error)
}

var _ Querier = (*Queries)(nil)
