postgres:
  addr: "127.0.0.1:5433"
  user: "github.com/dv-net/dv-merchant"
  password: ""
  db_name: "github.com/dv-net/dv-merchant"
redis:
  addr: "127.0.0.1:6380"
  user: ""
  password: ""
  db_index: 0