// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_exchange_chains

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	GetAll(ctx context.Context) ([]*GetAllRow, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.ExchangeChain, error)
	GetCurrencyIDByParams(ctx context.Context, arg GetCurrencyIDByParamsParams) (string, error)
	GetCurrencyIDBySlugAndChain(ctx context.Context, arg GetCurrencyIDBySlugAndChainParams) (string, error)
	GetCurrencyIDByTicker(ctx context.Context, ticker string) (string, error)
	GetEnabledCurrencies(ctx context.Context, slug models.ExchangeSlug) ([]*GetEnabledCurrenciesRow, error)
	GetTickerByCurrencyID(ctx context.Context, arg GetTickerByCurrencyIDParams) (string, error)
}

var _ Querier = (*Queries)(nil)
