// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_aml_service_keys

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.AmlServiceKey, error)
	GetAllByServiceSlug(ctx context.Context, slug models.AMLSlug) ([]*GetAllByServiceSlugRow, error)
}

var _ Querier = (*Queries)(nil)
