// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_exchanges

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Exchange, error)
	GetAll(ctx context.Context) ([]*models.Exchange, error)
	GetAllActiveWithUserKeys(ctx context.Context, userID uuid.UUID) ([]*GetAllActiveWithUserKeysRow, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.Exchange, error)
	GetExchangeBySlug(ctx context.Context, slug models.ExchangeSlug) (*models.Exchange, error)
	GetExchangeKeysBySlug(ctx context.Context, arg GetExchangeKeysBySlugParams) ([]*GetExchangeKeysBySlugRow, error)
}

var _ Querier = (*Queries)(nil)
