// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions_gen.sql

package repo_transactions

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const create = `-- name: Create :one
INSERT INTO transactions (user_id, store_id, receipt_id, wallet_id, currency_id, blockchain, tx_hash, bc_uniq_key, type, from_address, to_address, amount, amount_usd, fee, withdrawal_is_manual, network_created_at, created_at, created_at_index, is_system)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, now(), extract(epoch from now()) * 1000, $17)
	RETURNING id, user_id, store_id, receipt_id, wallet_id, currency_id, blockchain, tx_hash, bc_uniq_key, type, from_address, to_address, amount, amount_usd, fee, withdrawal_is_manual, network_created_at, created_at, updated_at, created_at_index, is_system
`

type CreateParams struct {
	UserID             uuid.UUID               `db:"user_id" json:"user_id"`
	StoreID            uuid.NullUUID           `db:"store_id" json:"store_id"`
	ReceiptID          uuid.NullUUID           `db:"receipt_id" json:"receipt_id"`
	WalletID           uuid.NullUUID           `db:"wallet_id" json:"wallet_id"`
	CurrencyID         string                  `db:"currency_id" json:"currency_id"`
	Blockchain         string                  `db:"blockchain" json:"blockchain"`
	TxHash             string                  `db:"tx_hash" json:"tx_hash"`
	BcUniqKey          *string                 `db:"bc_uniq_key" json:"bc_uniq_key"`
	Type               models.TransactionsType `db:"type" json:"type"`
	FromAddress        string                  `db:"from_address" json:"from_address"`
	ToAddress          string                  `db:"to_address" json:"to_address"`
	Amount             decimal.Decimal         `db:"amount" json:"amount"`
	AmountUsd          decimal.NullDecimal     `db:"amount_usd" json:"amount_usd"`
	Fee                decimal.Decimal         `db:"fee" json:"fee"`
	WithdrawalIsManual bool                    `db:"withdrawal_is_manual" json:"withdrawal_is_manual"`
	NetworkCreatedAt   pgtype.Timestamp        `db:"network_created_at" json:"network_created_at"`
	IsSystem           bool                    `db:"is_system" json:"is_system"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Transaction, error) {
	row := q.db.QueryRow(ctx, create,
		arg.UserID,
		arg.StoreID,
		arg.ReceiptID,
		arg.WalletID,
		arg.CurrencyID,
		arg.Blockchain,
		arg.TxHash,
		arg.BcUniqKey,
		arg.Type,
		arg.FromAddress,
		arg.ToAddress,
		arg.Amount,
		arg.AmountUsd,
		arg.Fee,
		arg.WithdrawalIsManual,
		arg.NetworkCreatedAt,
		arg.IsSystem,
	)
	var i models.Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.ReceiptID,
		&i.WalletID,
		&i.CurrencyID,
		&i.Blockchain,
		&i.TxHash,
		&i.BcUniqKey,
		&i.Type,
		&i.FromAddress,
		&i.ToAddress,
		&i.Amount,
		&i.AmountUsd,
		&i.Fee,
		&i.WithdrawalIsManual,
		&i.NetworkCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedAtIndex,
		&i.IsSystem,
	)
	return &i, err
}

const getById = `-- name: GetById :one
SELECT id, user_id, store_id, receipt_id, wallet_id, currency_id, blockchain, tx_hash, bc_uniq_key, type, from_address, to_address, amount, amount_usd, fee, withdrawal_is_manual, network_created_at, created_at, updated_at, created_at_index, is_system FROM transactions WHERE id=$1 LIMIT 1
`

func (q *Queries) GetById(ctx context.Context, id uuid.UUID) (*models.Transaction, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i models.Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.ReceiptID,
		&i.WalletID,
		&i.CurrencyID,
		&i.Blockchain,
		&i.TxHash,
		&i.BcUniqKey,
		&i.Type,
		&i.FromAddress,
		&i.ToAddress,
		&i.Amount,
		&i.AmountUsd,
		&i.Fee,
		&i.WithdrawalIsManual,
		&i.NetworkCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedAtIndex,
		&i.IsSystem,
	)
	return &i, err
}
