// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_notifications

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"

	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Notification, error)
	GetAllTypes(ctx context.Context) ([]*models.Notification, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.Notification, error)
}

var _ Querier = (*Queries)(nil)
