// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aml_checks.sql

package repo_aml_checks

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getByTransactionID = `-- name: GetByTransactionID :one
SELECT id, user_id, service_id, external_id, status, score, risk_level, created_at, updated_at, transaction_id
FROM aml_checks
WHERE transaction_id = $1
LIMIT 1
`

func (q *Queries) GetByTransactionID(ctx context.Context, transactionID uuid.NullUUID) (*models.AmlCheck, error) {
	row := q.db.QueryRow(ctx, getByTransactionID, transactionID)
	var i models.AmlCheck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.ExternalID,
		&i.Status,
		&i.Score,
		&i.RiskLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TransactionID,
	)
	return &i, err
}

const getStatistics = `-- name: GetStatistics :one
SELECT
    COUNT(*) FILTER (WHERE status IN ('success', 'failed')) AS checked_today,
    COUNT(*) FILTER (WHERE status = 'success') AS successful_today,
    COUNT(*) FILTER (WHERE status = 'failed') AS failed_today
FROM aml_checks
WHERE user_id = $1
  AND created_at >= $2::timestamp
  AND created_at < $3::timestamp
`

type GetStatisticsRow struct {
	CheckedToday    int64 `db:"checked_today" json:"checked_today"`
	SuccessfulToday int64 `db:"successful_today" json:"successful_today"`
	FailedToday     int64 `db:"failed_today" json:"failed_today"`
}

func (q *Queries) GetStatistics(ctx context.Context, userID uuid.UUID, dateFrom pgtype.Timestamp, dateTo pgtype.Timestamp) (*GetStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getStatistics, userID, dateFrom, dateTo)
	var i GetStatisticsRow
	err := row.Scan(&i.CheckedToday, &i.SuccessfulToday, &i.FailedToday)
	return &i, err
}

const updateAMLCheck = `-- name: UpdateAMLCheck :exec
UPDATE aml_checks
SET status     = $2,
    score      = $3,
    risk_level = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateAMLCheckParams struct {
	ID        uuid.UUID             `db:"id" json:"id"`
	Status    models.AMLCheckStatus `db:"status" json:"status"`
	Score     decimal.Decimal       `db:"score" json:"score"`
	RiskLevel *models.AmlRiskLevel  `db:"risk_level" json:"risk_level"`
}

func (q *Queries) UpdateAMLCheck(ctx context.Context, arg UpdateAMLCheckParams) error {
	_, err := q.db.Exec(ctx, updateAMLCheck,
		arg.ID,
		arg.Status,
		arg.Score,
		arg.RiskLevel,
	)
	return err
}

const updateExternalID = `-- name: UpdateExternalID :exec
UPDATE aml_checks
SET external_id = $2,
    updated_at  = now()
WHERE id = $1
`

func (q *Queries) UpdateExternalID(ctx context.Context, iD uuid.UUID, externalID string) error {
	_, err := q.db.Exec(ctx, updateExternalID, iD, externalID)
	return err
}
