// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aml_checks.sql

package repo_aml_checks

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getByTransactionID = `-- name: GetByTransactionID :one
SELECT id, user_id, service_id, external_id, status, score, risk_level, created_at, updated_at, transaction_id
FROM aml_checks
WHERE transaction_id = $1
LIMIT 1
`

func (q *Queries) GetByTransactionID(ctx context.Context, transactionID uuid.NullUUID) (*models.AmlCheck, error) {
	row := q.db.QueryRow(ctx, getByTransactionID, transactionID)
	var i models.AmlCheck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.ExternalID,
		&i.Status,
		&i.Score,
		&i.RiskLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TransactionID,
	)
	return &i, err
}

const updateAMLCheck = `-- name: UpdateAMLCheck :exec
UPDATE aml_checks
SET status     = $2,
    score      = $3,
    risk_level = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateAMLCheckParams struct {
	ID        uuid.UUID             `db:"id" json:"id"`
	Status    models.AMLCheckStatus `db:"status" json:"status"`
	Score     decimal.Decimal       `db:"score" json:"score"`
	RiskLevel *models.AmlRiskLevel  `db:"risk_level" json:"risk_level"`
}

func (q *Queries) UpdateAMLCheck(ctx context.Context, arg UpdateAMLCheckParams) error {
	_, err := q.db.Exec(ctx, updateAMLCheck,
		arg.ID,
		arg.Status,
		arg.Score,
		arg.RiskLevel,
	)
	return err
}
