// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aml_checks.sql

package repo_aml_checks

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const updateAMLCheck = `-- name: UpdateAMLCheck :exec
UPDATE aml_checks
SET status     = $2,
    score      = $3,
    risk_level = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateAMLCheckParams struct {
	ID        uuid.UUID             `db:"id" json:"id"`
	Status    models.AMLCheckStatus `db:"status" json:"status"`
	Score     decimal.Decimal       `db:"score" json:"score"`
	RiskLevel *models.AmlRiskLevel  `db:"risk_level" json:"risk_level"`
}

func (q *Queries) UpdateAMLCheck(ctx context.Context, arg UpdateAMLCheckParams) error {
	_, err := q.db.Exec(ctx, updateAMLCheck,
		arg.ID,
		arg.Status,
		arg.Score,
		arg.RiskLevel,
	)
	return err
}
