// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo_refund_requests

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.RefundRequest, error)
	GetAllByUserIDAndStatus(ctx context.Context, arg GetAllByUserIDAndStatusParams) ([]*models.RefundRequest, error)
	GetAllByWalletID(ctx context.Context, walletID uuid.UUID) ([]*models.RefundRequest, error)
	GetByBlockedTransactionID(ctx context.Context, blockedTransactionID uuid.UUID) (*models.RefundRequest, error)
	GetById(ctx context.Context, id uuid.UUID) (*models.RefundRequest, error)
	Update(ctx context.Context, arg UpdateParams) (*models.RefundRequest, error)
}

var _ Querier = (*Queries)(nil)
