// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refund_requests.sql

package repo_refund_requests

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

const getAllByStoreIDAndStatus = `-- name: GetAllByStoreIDAndStatus :many
SELECT id, blocked_transaction_id, wallet_id, store_id, transfer_id, destination_address, status, email, reviewed_at, created_at, updated_at
FROM refund_requests
WHERE store_id = $1
  AND status = $2
ORDER BY created_at DESC
`

type GetAllByStoreIDAndStatusParams struct {
	StoreID uuid.UUID `db:"store_id" json:"store_id"`
	Status  string    `db:"status" json:"status"`
}

func (q *Queries) GetAllByStoreIDAndStatus(ctx context.Context, arg GetAllByStoreIDAndStatusParams) ([]*models.RefundRequest, error) {
	rows, err := q.db.Query(ctx, getAllByStoreIDAndStatus, arg.StoreID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.RefundRequest{}
	for rows.Next() {
		var i models.RefundRequest
		if err := rows.Scan(
			&i.ID,
			&i.BlockedTransactionID,
			&i.WalletID,
			&i.StoreID,
			&i.TransferID,
			&i.DestinationAddress,
			&i.Status,
			&i.Email,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByBlockedTransactionID = `-- name: GetByBlockedTransactionID :one
SELECT id, blocked_transaction_id, wallet_id, store_id, transfer_id, destination_address, status, email, reviewed_at, created_at, updated_at
FROM refund_requests
WHERE blocked_transaction_id = $1
LIMIT 1
`

func (q *Queries) GetByBlockedTransactionID(ctx context.Context, blockedTransactionID uuid.UUID) (*models.RefundRequest, error) {
	row := q.db.QueryRow(ctx, getByBlockedTransactionID, blockedTransactionID)
	var i models.RefundRequest
	err := row.Scan(
		&i.ID,
		&i.BlockedTransactionID,
		&i.WalletID,
		&i.StoreID,
		&i.TransferID,
		&i.DestinationAddress,
		&i.Status,
		&i.Email,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
