// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refund_requests_gen.sql

package repo_refund_requests

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO refund_requests (blocked_transaction_id, wallet_id, store_id, transfer_id, destination_address, status, email, reviewed_at, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
	RETURNING id, blocked_transaction_id, wallet_id, store_id, transfer_id, destination_address, status, email, reviewed_at, created_at, updated_at
`

type CreateParams struct {
	BlockedTransactionID uuid.UUID        `db:"blocked_transaction_id" json:"blocked_transaction_id"`
	WalletID             uuid.UUID        `db:"wallet_id" json:"wallet_id"`
	StoreID              uuid.UUID        `db:"store_id" json:"store_id"`
	TransferID           uuid.NullUUID    `db:"transfer_id" json:"transfer_id"`
	DestinationAddress   string           `db:"destination_address" json:"destination_address"`
	Status               string           `db:"status" json:"status"`
	Email                string           `db:"email" json:"email"`
	ReviewedAt           pgtype.Timestamp `db:"reviewed_at" json:"reviewed_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.RefundRequest, error) {
	row := q.db.QueryRow(ctx, create,
		arg.BlockedTransactionID,
		arg.WalletID,
		arg.StoreID,
		arg.TransferID,
		arg.DestinationAddress,
		arg.Status,
		arg.Email,
		arg.ReviewedAt,
	)
	var i models.RefundRequest
	err := row.Scan(
		&i.ID,
		&i.BlockedTransactionID,
		&i.WalletID,
		&i.StoreID,
		&i.TransferID,
		&i.DestinationAddress,
		&i.Status,
		&i.Email,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAllByWalletID = `-- name: GetAllByWalletID :many
SELECT id, blocked_transaction_id, wallet_id, store_id, transfer_id, destination_address, status, email, reviewed_at, created_at, updated_at FROM refund_requests WHERE wallet_id=$1
`

func (q *Queries) GetAllByWalletID(ctx context.Context, walletID uuid.UUID) ([]*models.RefundRequest, error) {
	rows, err := q.db.Query(ctx, getAllByWalletID, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.RefundRequest{}
	for rows.Next() {
		var i models.RefundRequest
		if err := rows.Scan(
			&i.ID,
			&i.BlockedTransactionID,
			&i.WalletID,
			&i.StoreID,
			&i.TransferID,
			&i.DestinationAddress,
			&i.Status,
			&i.Email,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getById = `-- name: GetById :one
SELECT id, blocked_transaction_id, wallet_id, store_id, transfer_id, destination_address, status, email, reviewed_at, created_at, updated_at FROM refund_requests WHERE id=$1 LIMIT 1
`

func (q *Queries) GetById(ctx context.Context, id uuid.UUID) (*models.RefundRequest, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i models.RefundRequest
	err := row.Scan(
		&i.ID,
		&i.BlockedTransactionID,
		&i.WalletID,
		&i.StoreID,
		&i.TransferID,
		&i.DestinationAddress,
		&i.Status,
		&i.Email,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const update = `-- name: Update :one
UPDATE refund_requests
	SET transfer_id=$1, status=$2, reviewed_at=$3, updated_at=now()
WHERE id=$4
	RETURNING id, blocked_transaction_id, wallet_id, store_id, transfer_id, destination_address, status, email, reviewed_at, created_at, updated_at
`

type UpdateParams struct {
	TransferID uuid.NullUUID    `db:"transfer_id" json:"transfer_id"`
	Status     string           `db:"status" json:"status"`
	ReviewedAt pgtype.Timestamp `db:"reviewed_at" json:"reviewed_at"`
	ID         uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.RefundRequest, error) {
	row := q.db.QueryRow(ctx, update,
		arg.TransferID,
		arg.Status,
		arg.ReviewedAt,
		arg.ID,
	)
	var i models.RefundRequest
	err := row.Scan(
		&i.ID,
		&i.BlockedTransactionID,
		&i.WalletID,
		&i.StoreID,
		&i.TransferID,
		&i.DestinationAddress,
		&i.Status,
		&i.Email,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
