// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_store_whitelist

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"

	"github.com/google/uuid"
)

type Querier interface {
	CheckExistsByIP(ctx context.Context, arg CheckExistsByIPParams) (bool, error)
	Create(ctx context.Context, arg CreateParams) (*models.StoreWhitelist, error)
	Delete(ctx context.Context, storeID uuid.UUID) error
	DeleteByIP(ctx context.Context, arg DeleteByIPParams) error
	Find(ctx context.Context, storeID uuid.UUID) ([]*models.StoreWhitelist, error)
}

var _ Querier = (*Queries)(nil)
