// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_transfer_transactions

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
)

type Querier interface {
	BatchCreate(ctx context.Context, arg []BatchCreateParams) *BatchCreateBatchResults
	CalculateTransfersExpense(ctx context.Context, arg CalculateTransfersExpenseParams) ([]*CalculateTransfersExpenseRow, error)
	Create(ctx context.Context, arg CreateParams) (*models.TransferTransaction, error)
}

var _ Querier = (*Queries)(nil)
