// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store_aml_settings.sql

package repo_store_aml_settings

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

const getByStoreID = `-- name: GetByStoreID :one
SELECT id, store_id, enabled, risk_threshold, provider_slug, created_at, updated_at
FROM store_aml_settings
WHERE store_id = $1
limit 1
`

func (q *Queries) GetByStoreID(ctx context.Context, storeID uuid.UUID) (*models.StoreAmlSetting, error) {
	row := q.db.QueryRow(ctx, getByStoreID, storeID)
	var i models.StoreAmlSetting
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Enabled,
		&i.RiskThreshold,
		&i.ProviderSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsert = `-- name: Upsert :one
INSERT INTO store_aml_settings (store_id, enabled, risk_threshold, provider_slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (store_id) DO UPDATE
    SET enabled        = EXCLUDED.enabled,
        risk_threshold = EXCLUDED.risk_threshold,
        provider_slug  = EXCLUDED.provider_slug,
        updated_at     = now()
RETURNING id, store_id, enabled, risk_threshold, provider_slug, created_at, updated_at
`

type UpsertParams struct {
	StoreID       uuid.UUID       `db:"store_id" json:"store_id"`
	Enabled       bool            `db:"enabled" json:"enabled"`
	RiskThreshold int32           `db:"risk_threshold" json:"risk_threshold"`
	ProviderSlug  *models.AMLSlug `db:"provider_slug" json:"provider_slug"`
}

func (q *Queries) Upsert(ctx context.Context, arg UpsertParams) (*models.StoreAmlSetting, error) {
	row := q.db.QueryRow(ctx, upsert,
		arg.StoreID,
		arg.Enabled,
		arg.RiskThreshold,
		arg.ProviderSlug,
	)
	var i models.StoreAmlSetting
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Enabled,
		&i.RiskThreshold,
		&i.ProviderSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
