// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo_stores

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Store, error)
	GetArchivedByUser(ctx context.Context, userID uuid.UUID) ([]*models.Store, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.Store, error)
	GetByIDWithPublicFormEnabled(ctx context.Context, storeID uuid.UUID) (*models.Store, error)
	GetByUser(ctx context.Context, userID uuid.UUID) ([]*models.Store, error)
	GetStatisticsByStoreIDs(ctx context.Context, storeIds []uuid.UUID) ([]*GetStatisticsByStoreIDsRow, error)
	GetStoreByStoreApiKey(ctx context.Context, key string) (*models.Store, error)
	GetStoreByWalletAddress(ctx context.Context, arg GetStoreByWalletAddressParams) (*GetStoreByWalletAddressRow, error)
	GetStoreByWalletID(ctx context.Context, id uuid.UUID) (*models.Store, error)
	GetStoreCurrencies(ctx context.Context, storeID uuid.UUID) ([]*models.Currency, error)
	ResendStoreVerification(ctx context.Context, arg ResendStoreVerificationParams) (*models.Store, error)
	Restore(ctx context.Context, id uuid.UUID) error
	SoftDelete(ctx context.Context, id uuid.UUID) error
	Update(ctx context.Context, arg UpdateParams) (*models.Store, error)
	UpdateRate(ctx context.Context, arg UpdateRateParams) error
	UpdateVerificationStatus(ctx context.Context, arg UpdateVerificationStatusParams) (*models.Store, error)
}

var _ Querier = (*Queries)(nil)
