// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_logs

import (
	"context"
	"github.com/dv-net/dv-merchant/internal/models"

	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Log, error)
	DeleteLogBySlug(ctx context.Context, arg DeleteLogBySlugParams) error
	GetByID(ctx context.Context, id uuid.UUID) (*models.Log, error)
	GetByProcessID(ctx context.Context, processID uuid.UUID) (*models.Log, error)
	GetLogsBySlug(ctx context.Context, logTypeSlug string) ([]*GetLogsBySlugRow, error)
	Update(ctx context.Context, arg UpdateParams) (*models.Log, error)
}

var _ Querier = (*Queries)(nil)
