// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_exchange_user_keys

import (
	"context"

	"github.com/dv-net/dv-merchant/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	BatchDeleteByID(ctx context.Context, id []uuid.UUID) *BatchDeleteByIDBatchResults
	Create(ctx context.Context, arg CreateParams) (*models.ExchangeUserKey, error)
	CreateOrUpdateUserKey(ctx context.Context, arg CreateOrUpdateUserKeyParams) (*models.ExchangeUserKey, error)
	DeleteByID(ctx context.Context, id uuid.UUID) error
	GetKeysByExchangeSlug(ctx context.Context, arg GetKeysByExchangeSlugParams) ([]*GetKeysByExchangeSlugRow, error)
}

var _ Querier = (*Queries)(nil)
