INSERT INTO exchange_chains (slug, currency_id, ticker, chain)
values
    ('okx','BTC.Bitcoin', 'BTC', 'BTC-Bitcoin'),
    ('okx','ETH.Ethereum', 'ETH', 'ETH-ERC20'),
    ('okx','TRX.Tron', 'TRX', 'TRX-TRC20'),
    ('okx','USDT.Ethereum', 'USDT', 'USDT-ERC20'),
    ('okx','USDT.Tron', 'USDT', 'USDT-TRC20'),
    ('okx','LTC.Litecoin', 'LTC', 'LTC-Litecoin'),
    ('okx', 'BCH.Bitcoincash', 'BCH', 'BCH-BitcoinCash'),
    ('okx', 'DAI.Ethereum', 'DAI', 'DAI-ERC20'),
    ('okx', 'BNB.BNBSmartChain', 'BNB', 'BNB-BSC'),
    ('okx','USDT.Polygon', 'USDT', 'USDT-Polygon'),
    ('okx','POL.Polygon', 'POL', 'POL-Polygon'),
    ('okx','DAI.Polygon', 'DAI', 'DAI-Polygon'),
    ('okx','SAND.Ethereum', 'SAND', 'SAND-ERC20'),
    ('okx','ENA.Ethereum', 'ENA', 'ENA-ERC20'),
    ('okx','PEPE.Ethereum', 'PEPE', 'PEPE-ERC20'),
    ('okx','SHIB.Ethereum', 'SHIB', 'SHIB-ERC20'),
    ('okx','WLD.Ethereum', 'WLD', 'WLD-ERC20'),
    ('okx','WLFI.Ethereum', 'WLFI', 'WLFI-ERC20'),
    ('okx','XAUT.Ethereum', 'XAUT', 'XAUT-ERC20'),
    ('htx','BTC.Bitcoin', 'btc', 'btc'),
    ('htx','ETH.Ethereum', 'eth', 'eth'),
    ('htx','TRX.Tron', 'trx', 'trx1'),
    ('htx','USDT.Ethereum', 'usdt', 'usdterc20'),
    ('htx','USDT.Tron', 'usdt', 'trc20usdt'),
    ('htx','USDC.Ethereum', 'usdc', 'usdc'),
    ('htx','LTC.Litecoin', 'ltc', 'ltc'),
    ('htx', 'BCH.Bitcoincash', 'bch', 'bcc'),
    ('htx', 'DAI.Ethereum', 'dai', 'dai'),
    ('htx', 'BNB.BNBSmartChain', 'bnb', 'bnb1'),
    ('htx', 'USDT.BNBSmartChain', 'usdt', 'bep20usdt'),
    ('htx', 'USDC.BNBSmartChain', 'usdc', 'bep20usdc'),
    ('htx', 'DAI.BNBSmartChain', 'dai', 'bep20dai'),
    ('htx', 'POL.Polygon', 'pol', 'matic1'),
    ('htx', 'SAND.Ethereum', 'sand', 'sand'),
    ('htx', 'XAUT.Ethereum', 'xaut', 'xaut'),
    ('htx', 'PYUSD.Ethereum', 'pyusd', 'pyusd'),
    ('htx', 'WLD.Ethereum', 'wld', 'erc20wld'),
    ('htx', 'USD1.Ethereum', 'usd1', 'erc20usd1'),
    ('htx', 'USD1.BNBSmartChain', 'usd1', 'usd1'),
    ('htx', 'USD1.Tron', 'usd1', 'trc20usd1'),
    ('htx', 'WLFI.Ethereum', 'wlfi', 'erc20wlfi'),
    ('htx', 'ENA.Ethereum', 'ena', 'ena'),
    ('htx', 'PEPE.Ethereum', 'pepe', 'pepe'),
    ('htx', 'SHIB.Ethereum', 'shib', 'shib'),
    ('htx', 'SHIB.BNBSmartChain', 'shib', 'bep20shib'),
    ('htx', 'CAKE.BNBSmartChain', 'cake', 'cake'),
    ('binance', 'BTC.Bitcoin', 'BTC', 'BTC'),
    ('binance', 'ETH.Ethereum', 'ETH', 'ETH'),
    ('binance', 'TRX.Tron', 'TRX', 'TRX'),
    ('binance', 'USDT.Ethereum', 'USDT', 'ETH'),
    ('binance', 'USDT.Tron', 'USDT', 'TRX'),
    ('binance', 'USDC.Ethereum', 'USDC', 'ETH'),
    ('binance', 'LTC.Litecoin', 'LTC', 'LTC'),
    ('binance', 'BCH.Bitcoincash', 'BCH', 'BCH'),
    ('binance', 'DAI.Ethereum', 'DAI', 'ETH'),
    ('binance', 'BNB.BNBSmartChain', 'BNB', 'BSC'),
    ('binance', 'USDT.BNBSmartChain', 'USDT', 'BSC'),
    ('binance', 'USDC.BNBSmartChain', 'USDC', 'BSC'),
    ('binance', 'DAI.BNBSmartChain', 'DAI', 'BSC'),
    ('binance', 'POL.Polygon', 'POL', 'MATIC'),
    ('binance', 'DAI.Polygon', 'DAI', 'MATIC'),
    ('binance', 'USDC.Polygon', 'USDC', 'MATIC'),
    ('binance', 'USDT.Polygon', 'USDT', 'MATIC'),
    ('binance', 'SAND.Ethereum', 'SAND', 'ETH'),
    ('binance', 'SAND.Polygon', 'SAND', 'MATIC'),
    ('binance', 'SAND.BNBSmartChain', 'SAND', 'BSC'),
    ('binance', 'WLD.Ethereum', 'WLD', 'ETH'),
    ('binance', 'USD1.Ethereum', 'USD1', 'ETH'),
    ('binance', 'USD1.BNBSmartChain', 'USD1', 'BSC'),
    ('binance', 'WLFI.Ethereum', 'WLFI', 'ETH'),
    ('binance', 'WLFI.BNBSmartChain', 'WLFI', 'BSC'),
    ('binance', 'ENA.Ethereum', 'ENA', 'ETH'),
    ('binance', 'USDE.Ethereum', 'USDE', 'ETH'),
    ('binance', 'USDE.BNBSmartChain', 'USDE', 'BSC'),
    ('binance', 'PEPE.Ethereum', 'PEPE', 'ETH'),
    ('binance', 'SHIB.Ethereum', 'SHIB', 'ETH'),
    ('binance', 'SHIB.BNBSmartChain', 'SHIB', 'BSC'),
    ('binance', 'CAKE.Ethereum', 'CAKE', 'ETH'),
    ('binance', 'CAKE.BNBSmartChain', 'CAKE', 'BSC'),
    ('bitget', 'BTC.Bitcoin', 'BTC', 'BTC'),
    ('bitget', 'ETH.Ethereum', 'ETH', 'ETH'),
    ('bitget', 'TRX.Tron', 'TRX', 'TRX'),
    ('bitget', 'USDT.Ethereum', 'USDT', 'ERC20'),
    ('bitget', 'USDT.Tron', 'USDT', 'TRC20'),
    ('bitget', 'USDC.Ethereum', 'USDC', 'ERC20'),
    ('bitget', 'LTC.Litecoin', 'LTC', 'LTC'),
    ('bitget', 'BCH.Bitcoincash', 'BCH', 'BCH'),
    ('bitget', 'DAI.Ethereum', 'DAI', 'ERC20'),
    ('bitget', 'BNB.BNBSmartChain', 'BNB', 'BEP20'),
    ('bitget', 'USDT.BNBSmartChain', 'USDT', 'BEP20'),
    ('bitget', 'USDC.BNBSmartChain', 'USDC', 'BEP20'),
    ('bitget', 'DAI.BNBSmartChain', 'DAI', 'BEP20'),
    ('bitget', 'DAI.BNBSmartChain', 'DAI', 'BEP20'),
    ('bitget', 'POL.Polygon', 'POL', 'Polygon'),
    ('bitget', 'USDT.Polygon', 'USDT', 'Polygon'),
    ('bitget', 'USDC.Polygon', 'USDC', 'POLYGON'),
    ('bitget', 'DAI.Polygon', 'DAI', 'Polygon'),
    ('bitget', 'DAI.BNBSmartChain', 'DAI', 'BEP20'),
    ('bitget', 'SAND.Ethereum', 'SAND', 'ERC20'),
    ('bitget', 'XAUT.Ethereum', 'XAUT', 'ERC20'),
    ('bitget', 'PYUSD.Ethereum', 'PYUSD', 'ERC20'),
    ('bitget', 'WLD.Ethereum', 'WLD', 'ERC20'),
    ('bitget', 'USD1.Ethereum', 'USD1', 'ERC20'),
    ('bitget', 'USD1.BNBSmartChain', 'USD1', 'BEP20'),
    ('bitget', 'WLFI.Ethereum', 'WLFI', 'ERC20'),
    ('bitget', 'ENA.Ethereum', 'ENA', 'ERC20'),
    ('bitget', 'PEPE.Ethereum', 'PEPE', 'ERC20'),
    ('bitget', 'SHIB.Ethereum', 'SHIB', 'ERC20'),
    ('bitget', 'SHIB.BNBSmartChain', 'SHIB', 'BEP20'),
    ('bitget', 'CAKE.BNBSmartChain', 'CAKE', 'BEP20'),
    ('bitget', 'USDE.Ethereum', 'USDE', 'ERC20'),
    ('kucoin', 'BTC.Bitcoin', 'BTC', 'btc'),
    ('kucoin', 'ETH.Ethereum', 'ETH', 'eth'),
    ('kucoin', 'ETH.Arbitrum', 'ETH', 'arbitrum'),
    ('kucoin', 'TRX.Tron', 'TRX', 'trx'),
    ('kucoin', 'USDT.Ethereum', 'USDT', 'eth'),
    ('kucoin', 'USDT.Tron', 'USDT', 'trx'),
    ('kucoin', 'USDC.Ethereum', 'USDC', 'eth'),
    ('kucoin', 'USDC.Arbitrum', 'USDC', 'arbitrum'),
    ('kucoin', 'USDT.Arbitrum', 'USDT', 'arbitrum'),
    ('kucoin', 'LTC.Litecoin', 'LTC', 'ltc'),
    ('kucoin', 'BCH.Bitcoincash', 'BCH', 'bchn'),
    ('kucoin', 'DAI.Ethereum', 'DAI', 'eth'),
    ('kucoin', 'BNB.BNBSmartChain', 'BNB', 'bsc'),
    ('kucoin', 'USDT.BNBSmartChain', 'USDT', 'bsc'),
    ('kucoin', 'USDT.Polygon', 'USDT', 'matic'),
    ('kucoin', 'POL.Polygon', 'POL', 'matic'),
    ('kucoin', 'CAKE.BNBSmartChain', 'CAKE', 'bsc'),
    ('kucoin', 'SAND.Ethereum', 'SAND', 'eth'),
    ('kucoin', 'SHIB.Ethereum', 'SHIB', 'eth'),
    ('kucoin', 'PEPE.Ethereum', 'PEPE', 'eth'),
    ('kucoin', 'WLD.Ethereum', 'WLD', 'eth'),
    ('kucoin', 'PYUSD.Ethereum', 'PYUSD', 'eth'),
    ('kucoin', 'ENA.Ethereum', 'ENA', 'eth'),
    ('kucoin', 'USDE.Ethereum', 'USDE', 'eth'),
    ('kucoin', 'USD1.BNBSmartChain', 'USD1', 'bsc'),
    ('kucoin', 'USD1.Ethereum', 'USD1', 'eth'),
    ('kucoin', 'USD1.Tron', 'USD1', 'trx'),
    ('kucoin', 'XAUT.Ethereum', 'XAUT', 'eth'),
    ('kucoin', 'WLFI.BNBSmartChain', 'WLFI', 'bsc'),
    ('kucoin', 'WLFI.Ethereum', 'WLFI', 'eth'),
    ('bybit', 'BTC.Bitcoin', 'BTC', 'BTC'),
    ('bybit', 'ETH.Ethereum', 'ETH', 'ETH'),
    ('bybit', 'ETH.Arbitrum', 'ETH', 'ARBI'),
    ('bybit', 'TRX.Tron', 'TRX', 'TRX'),
    ('bybit', 'LTC.Litecoin', 'LTC', 'LTC'),
    ('bybit', 'BCH.Bitcoincash', 'BCH', 'BCH'),
    ('bybit', 'USDT.Tron', 'USDT', 'TRX'),
    ('bybit', 'USDT.BNBSmartChain', 'USDT', 'BSC'),
    ('bybit', 'USDT.Ethereum', 'USDT', 'ETH'),
    ('bybit', 'USDT.Polygon', 'USDT', 'MATIC'),
    ('bybit', 'USDT.Arbitrum', 'USDT', 'ARBI'),
    ('bybit', 'USDC.Ethereum', 'USDC', 'ETH'),
    ('bybit', 'USDC.Arbitrum', 'USDC', 'ARBI'),
    ('bybit', 'USDC.BNBSmartChain', 'USDC', 'BSC'),
    ('bybit', 'USDC.Polygon', 'USDC', 'MATIC'),
    ('bybit', 'DAI.Ethereum', 'DAI', 'ETH'),
    ('bybit', 'DAI.BNBSmartChain', 'DAI', 'BSC'),
    ('bybit', 'BNB.BNBSmartChain', 'BNB', 'BSC'),
    ('bybit', 'POL.Polygon', 'POL', 'MATIC'),
    ('bybit', 'DOGE.Dogecoin', 'DOGE', 'DOGE'),
    ('bybit', 'SAND.Ethereum', 'SAND', 'ETH'),
    ('bybit', 'XAUT.Ethereum', 'XAUT', 'ETH'),
    ('bybit', 'PYUSD.Ethereum', 'PYUSD', 'ETH'),
    ('bybit', 'WLD.Ethereum', 'WLD', 'ETH'),
    ('bybit', 'USD1.Ethereum', 'USD1', 'ETH'),
    ('bybit', 'USD1.BNBSmartChain', 'USD1', 'BSC'),
    ('bybit', 'USD1.Tron', 'USD1', 'TRX'),
    ('bybit', 'WLFI.Ethereum', 'WLFI', 'ETH'),
    ('bybit', 'ENA.Ethereum', 'ENA', 'ETH'),
    ('bybit', 'PEPE.Ethereum', 'PEPE', 'ETH'),
    ('bybit', 'SHIB.Ethereum', 'SHIB', 'ETH'),
    ('bybit', 'SHIB.BNBSmartChain', 'SHIB', 'BSC'),
    ('bybit', 'CAKE.BNBSmartChain', 'CAKE', 'BSC'),
    ('bybit', 'USDE.Ethereum', 'USDE', 'ETH'),
    ('gate', 'BTC.Bitcoin', 'BTC', 'BTC'),
    ('gate', 'BCH.Bitcoincash', 'BCH', 'BCH'),
    ('gate', 'LTC.Litecoin', 'LTC', 'LTC'),
    ('gate', 'ETH.Ethereum', 'ETH', 'ETH'),
    ('gate', 'TRX.Tron', 'TRX', 'TRX'),
    ('gate', 'USDT.Ethereum', 'USDT', 'ETH'),
    ('gate', 'USDT.Polygon', 'USDT', 'MATIC'),
    ('gate', 'USDT.Tron', 'USDT', 'TRX'),
    ('gate', 'USDT.BNBSmartChain', 'USDT', 'BSC'),
    ('gate', 'USDC.Ethereum', 'USDC', 'ETH'),
    ('gate', 'USDC.BNBSmartChain', 'USDC', 'BSC'),
    ('gate', 'USDC.Polygon', 'USDC', 'MATIC'),
    ('gate', 'BNB.BNBSmartChain', 'BNB', 'BSC'),
    ('gate', 'DAI.Ethereum', 'DAI', 'ETH'),
    ('gate', 'DAI.Polygon', 'DAI', 'MATIC'),
    ('gate', 'POL.Polygon', 'POL', 'MATIC'),
    ('gate', 'ENA.Ethereum', 'ENA', 'ETH'),
    ('gate', 'WLD.Ethereum', 'WLD', 'ETH'),
    ('gate', 'SHIB.Ethereum', 'SHIB', 'ETH'),
    ('gate', 'USD1.Ethereum', 'USD1', 'ETH'),
    ('gate', 'USD1.BNBSmartChain', 'USD1', 'BSC'),
    ('gate', 'USD1.Tron', 'USD1', 'TRX'),
    ('gate', 'USDE.Ethereum', 'USD1', 'ETH'),
    ('gate', 'PEPE.Ethereum', 'PEPE', 'ETH'),
    ('gate', 'CAKE.BNBSmartChain', 'CAKE', 'BSC'),
    ('gate', 'WLFI.Ethereum', 'WLFI', 'ETH'),
    ('gate', 'WLFI.BNBSmartChain', 'WLFI', 'BSC'),
    ('gate', 'SAND.Ethereum', 'SAND', 'ETH'),
    ('gate', 'XAUT.Ethereum', 'XAUT', 'ETH')
ON CONFLICT DO NOTHING;
