INSERT INTO exchange_chains (slug, currency_id, ticker, chain)
values
    ('okx','BTC.Bitcoin', 'BTC', 'BTC-Bitcoin'),
    ('okx','ETH.Ethereum', 'ETH', 'ETH-ERC20'),
    ('okx','TRX.Tron', 'TRX', 'TRX-TRC20'),
    ('okx','USDT.Ethereum', 'USDT', 'USDT-ERC20'),
    ('okx','USDT.Tron', 'USDT', 'USDT-TRC20'),
    ('okx','LTC.Litecoin', 'LTC', 'LTC-Litecoin'),
    ('okx', 'BCH.Bitcoincash', 'BCH', 'BCH-BitcoinCash'),
    ('okx', 'DAI.Ethereum', 'DAI', 'DAI-ERC20'),
    ('okx', 'BNB.BNBSmartChain', 'BNB', 'BNB-BSC'),
    ('okx','USDT.Polygon', 'USDT', 'USDT-Polygon'),
    ('okx','POL.Polygon', 'POL', 'POL-Polygon'),
    ('okx','DAI.Polygon', 'DAI', 'DAI-Polygon'),
    ('okx','SAND.Ethereum', 'SAND', 'SAND-ERC20'),
    ('okx','ENA.Ethereum', 'ENA', 'ENA-ERC20'),
    ('okx','PEPE.Ethereum', 'PEPE', 'PEPE-ERC20'),
    ('okx','SHIB.Ethereum', 'SHIB', 'SHIB-ERC20'),
    ('okx','WLD.Ethereum', 'WLD', 'WLD-ERC20'),
    ('okx','WLFI.Ethereum', 'WLFI', 'WLFI-ERC20'),
    ('okx','XAUT.Ethereum', 'XAUT', 'XAUT-ERC20'),
    ('htx','BTC.Bitcoin', 'btc', 'btc'),
    ('htx','ETH.Ethereum', 'eth', 'eth'),
    ('htx','TRX.Tron', 'trx', 'trx1'),
    ('htx','USDT.Ethereum', 'usdt', 'usdterc20'),
    ('htx','USDT.Tron', 'usdt', 'trc20usdt'),
    ('htx','USDC.Ethereum', 'usdc', 'usdc'),
    ('htx','LTC.Litecoin', 'ltc', 'ltc'),
    ('htx', 'BCH.Bitcoincash', 'bch', 'bcc'),
    ('htx', 'DAI.Ethereum', 'dai', 'dai'),
    ('htx', 'BNB.BNBSmartChain', 'bnb', 'bnb1'),
    ('htx', 'USDT.BNBSmartChain', 'usdt', 'bep20usdt'),
    ('htx', 'USDC.BNBSmartChain', 'usdc', 'bep20usdc'),
    ('htx', 'DAI.BNBSmartChain', 'dai', 'bep20dai'),
    ('htx', 'POL.Polygon', 'pol', 'matic1'),
    ('binance', 'BTC.Bitcoin', 'BTC', 'BTC'),
    ('binance', 'ETH.Ethereum', 'ETH', 'ETH'),
    ('binance', 'TRX.Tron', 'TRX', 'TRX'),
    ('binance', 'USDT.Ethereum', 'USDT', 'ETH'),
    ('binance', 'USDT.Tron', 'USDT', 'TRX'),
    ('binance', 'USDC.Ethereum', 'USDC', 'ETH'),
    ('binance', 'LTC.Litecoin', 'LTC', 'LTC'),
    ('binance', 'BCH.Bitcoincash', 'BCH', 'BCH'),
    ('binance', 'DAI.Ethereum', 'DAI', 'ETH'),
    ('binance', 'BNB.BNBSmartChain', 'BNB', 'BSC'),
    ('binance', 'USDT.BNBSmartChain', 'USDT', 'BSC'),
    ('binance', 'USDC.BNBSmartChain', 'USDC', 'BSC'),
    ('binance', 'DAI.BNBSmartChain', 'DAI', 'BSC'),
    ('binance', 'POL.Polygon', 'POL', 'MATIC'),
    ('binance', 'DAI.Polygon', 'DAI', 'MATIC'),
    ('binance', 'USDC.Polygon', 'USDC', 'MATIC'),
    ('binance', 'USDT.Polygon', 'USDT', 'MATIC'),
    ('bitget', 'BTC.Bitcoin', 'BTC', 'BTC'),
    ('bitget', 'ETH.Ethereum', 'ETH', 'ETH'),
    ('bitget', 'TRX.Tron', 'TRX', 'TRX'),
    ('bitget', 'USDT.Ethereum', 'USDT', 'ERC20'),
    ('bitget', 'USDT.Tron', 'USDT', 'TRC20'),
    ('bitget', 'USDC.Ethereum', 'USDC', 'ERC20'),
    ('bitget', 'LTC.Litecoin', 'LTC', 'LTC'),
    ('bitget', 'BCH.Bitcoincash', 'BCH', 'BCH'),
    ('bitget', 'DAI.Ethereum', 'DAI', 'ERC20'),
    ('bitget', 'BNB.BNBSmartChain', 'BNB', 'BEP20'),
    ('bitget', 'USDT.BNBSmartChain', 'USDT', 'BEP20'),
    ('bitget', 'USDC.BNBSmartChain', 'USDC', 'BEP20'),
    ('bitget', 'DAI.BNBSmartChain', 'DAI', 'BEP20'),
    ('bitget', 'DAI.BNBSmartChain', 'DAI', 'BEP20'),
    ('bitget', 'POL.Polygon', 'POL', 'Polygon'),
    ('bitget', 'USDT.Polygon', 'USDT', 'Polygon'),
    ('bitget', 'USDC.Polygon', 'USDC', 'POLYGON'),
    ('bitget', 'DAI.Polygon', 'DAI', 'Polygon'),
    ('bitget', 'DAI.BNBSmartChain', 'DAI', 'BEP20'),
    ('kucoin', 'BTC.Bitcoin', 'BTC', 'btc'),
    ('kucoin', 'ETH.Ethereum', 'ETH', 'eth'),
    ('kucoin', 'ETH.Arbitrum', 'ETH', 'arbitrum'),
    ('kucoin', 'TRX.Tron', 'TRX', 'trx'),
    ('kucoin', 'USDT.Ethereum', 'USDT', 'eth'),
    ('kucoin', 'USDT.Tron', 'USDT', 'trx'),
    ('kucoin', 'USDC.Ethereum', 'USDC', 'eth'),
    ('kucoin', 'USDC.Arbitrum', 'USDC', 'arbitrum'),
    ('kucoin', 'USDT.Arbitrum', 'USDT', 'arbitrum'),
    ('kucoin', 'LTC.Litecoin', 'LTC', 'ltc'),
    ('kucoin', 'BCH.Bitcoincash', 'BCH', 'bchn'),
    ('kucoin', 'DAI.Ethereum', 'DAI', 'eth'),
    ('kucoin', 'BNB.BNBSmartChain', 'BNB', 'bsc'),
    ('kucoin', 'USDT.BNBSmartChain', 'USDT', 'bsc'),
    ('kucoin', 'USDT.Polygon', 'USDT', 'matic'),
    ('kucoin', 'POL.Polygon', 'POL', 'matic'),
    ('bybit', 'BTC.Bitcoin', 'BTC', 'BTC'),
    ('bybit', 'ETH.Ethereum', 'ETH', 'ETH'),
    ('bybit', 'ETH.Arbitrum', 'ETH', 'ARBI'),
    ('bybit', 'TRX.Tron', 'TRX', 'TRX'),
    ('bybit', 'LTC.Litecoin', 'LTC', 'LTC'),
    ('bybit', 'BCH.Bitcoincash', 'BCH', 'BCH'),
    ('bybit', 'USDT.Tron', 'USDT', 'TRX'),
    ('bybit', 'USDT.BNBSmartChain', 'USDT', 'BSC'),
    ('bybit', 'USDT.Ethereum', 'USDT', 'ETH'),
    ('bybit', 'USDT.Polygon', 'USDT', 'MATIC'),
    ('bybit', 'USDT.Arbitrum', 'USDT', 'ARBI'),
    ('bybit', 'USDC.Ethereum', 'USDC', 'ETH'),
    ('bybit', 'USDC.Arbitrum', 'USDC', 'ARBI'),
    ('bybit', 'USDC.BNBSmartChain', 'USDC', 'BSC'),
    ('bybit', 'USDC.Polygon', 'USDC', 'MATIC'),
    ('bybit', 'DAI.Ethereum', 'DAI', 'ETH'),
    ('bybit', 'DAI.BNBSmartChain', 'DAI', 'BSC'),
    ('bybit', 'BNB.BNBSmartChain', 'BNB', 'BSC'),
    ('bybit', 'POL.Polygon', 'POL', 'MATIC'),
    ('bybit', 'DOGE.Dogecoin', 'DOGE', 'DOGE'),
    ('gate', 'BTC.Bitcoin', 'BTC', 'BTC'),
    ('gate', 'BCH.Bitcoincash', 'BCH', 'BCH'),
    ('gate', 'LTC.Litecoin', 'LTC', 'LTC'),
    ('gate', 'ETH.Ethereum', 'ETH', 'ETH'),
    ('gate', 'TRX.Tron', 'TRX', 'TRX'),
    ('gate', 'USDT.Ethereum', 'USDT', 'ETH'),
    ('gate', 'USDT.Polygon', 'USDT', 'MATIC'),
    ('gate', 'USDT.Tron', 'USDT', 'TRX'),
    ('gate', 'USDT.BNBSmartChain', 'USDT', 'BSC'),
    ('gate', 'USDC.Ethereum', 'USDC', 'ETH'),
    ('gate', 'USDC.BNBSmartChain', 'USDC', 'BSC'),
    ('gate', 'USDC.Polygon', 'USDC', 'MATIC'),
    ('gate', 'BNB.BNBSmartChain', 'BNB', 'BSC'),
    ('gate', 'DAI.Ethereum', 'DAI', 'ETH'),
    ('gate', 'DAI.Polygon', 'DAI', 'MATIC'),
    ('gate', 'POL.Polygon', 'POL', 'MATIC')
ON CONFLICT DO NOTHING;
